parameters:
  images_directory: "%kernel.project_dir%/public/uploads/images/"
  openai_api_key: "%env(OPENAI_API_KEY)%"
  tts_model: "%env(TTS_MODEL)%"
  voice_default: '%env(VOICE_DEFAULT)%'

services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\:
    resource: "../src/"
    exclude:
      - "../src/DependencyInjection/"
      - "../src/Entity/"
      - "../src/Kernel.php"

  App\Service\TextToSpeechService:
    arguments:
      $apiKey: '%openai_api_key%'
      $model: '%tts_model%'
      $defaultVoice: '%voice_default%'
